name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python train.py
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/test_model.py -v
        
    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/ 